name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend deps and build
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist

  build-backend-image:
    runs-on: ubuntu-latest
    needs: build-and-deploy-frontend

    steps:
      - uses: actions/checkout@v4

      - name: Build backend Docker image
        working-directory: backend
        run: |
          docker build -t backend-image:latest .

      - name: Save image as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: backend-image
          path: |
            backend-image.tar || true

  optional-deploy-to-render:
    runs-on: ubuntu-latest
    needs: build-backend-image
    if: ${{ secrets.RENDER_API_KEY != '' }}

    steps:
      - name: Trigger Render deploy (requires RENDER_API_KEY)
        run: |
          echo "This step would call Render's API to trigger a deploy if configured."
